obj-y			+= modem.o modem_io_device.o modem_net_flowcontrol_device.o
obj-$(CONFIG_UMTS_MODEM_XMM6260) += modem_modemctl_device_xmm6260.o
obj-$(CONFIG_UMTS_LINK_MIPI) += modem_link_device_mipi.o
obj-$(CONFIG_UMTS_LINK_HSIC) += modem_link_device_hsic.o
obj-$(CONFIG_CDMA_MODEM_CBP71) += modem_modemctl_device_cbp71.o
obj-$(CONFIG_CDMA_LINK_DPRAM) += modem_link_device_dpram.o
obj-$(CONFIG_LTE_MODEM_CMC221) += modem_modemctl_device_cmc221.o lte_modem_bootloader.o
obj-$(CONFIG_LTE_LINK_USB) += modem_link_device_usb.o
