obj-$(CONFIG_RPMSG)	+= virtio_rpmsg_bus.o

obj-$(CONFIG_RPMSG_OMX) += rpmsg_omx.o
obj-$(CONFIG_RPMSG_CLIENT_SAMPLE) += rpmsg_client_sample.o
obj-$(CONFIG_RPMSG_SERVER_SAMPLE) += rpmsg_server_sample.o
obj-$(CONFIG_RPMSG_RESMGR) += rpmsg_resmgr.o
